services:

  backend:

    image: realutkarshh/ai-crm-backend:${BACKEND_TAG}

    container_name: crm-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env.production

    expose:
      - "8000"

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:

    image: realutkarshh/ai-crm-frontend:${FRONTEND_TAG}

    container_name: crm-frontend

    restart: unless-stopped

    depends_on:
      backend:
        condition: service_healthy

    ports:
      - "80:80"